<?php

namespace Database\Seeders;


use App\Models\Dashboard\Country\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'en' => 'Afghanistan',
                'ar' => 'أفغانستان',
                'iso_code' => 'AF',
                'dial_code' => '+93',
            ],
            [
                'en' => 'Albania',
                'ar' => 'ألبانيا',
                'iso_code' => 'AL',
                'dial_code' => '+355',
            ],
            [
                'en' => 'Algeria',
                'ar' => 'الجزائر',
                'iso_code' => 'DZ',
                'dial_code' => '+213',
            ],
            [
                'en' => 'Andorra',
                'ar' => 'أندورا',
                'iso_code' => 'AD',
                'dial_code' => '+376',
            ],
            [
                'en' => 'Angola',
                'ar' => 'أنغولا',
                'iso_code' => 'AO',
                'dial_code' => '+244',
            ],
            [
                'en' => 'Antigua and Barbuda',
                'ar' => 'أنتيغوا وباربودا',
                'iso_code' => 'AG',
                'dial_code' => '+1268',
            ],
            [
                'en' => 'Argentina',
                'ar' => 'الأرجنتين',
                'iso_code' => 'AR',
                'dial_code' => '+54',
            ],
            [
                'en' => 'Armenia',
                'ar' => 'أرمينيا',
                'iso_code' => 'AM',
                'dial_code' => '+374',
            ],
            [
                'en' => 'Australia',
                'ar' => 'أستراليا',
                'iso_code' => 'AU',
                'dial_code' => '+61',
            ],
            [
                'en' => 'Austria',
                'ar' => 'النمسا',
                'iso_code' => 'AT',
                'dial_code' => '+43',
            ],
            [
                'en' => 'Azerbaijan',
                'ar' => 'أذربيجان',
                'iso_code' => 'AZ',
                'dial_code' => '+994',
            ],
            [
                'en' => 'Bahamas',
                'ar' => 'الباهاما',
                'iso_code' => 'BS',
                'dial_code' => '+1242',
            ],
            [
                'en' => 'Bahrain',
                'ar' => 'البحرين',
                'iso_code' => 'BH',
                'dial_code' => '+973',
            ],
            [
                'en' => 'Bangladesh',
                'ar' => 'بنغلاديش',
                'iso_code' => 'BD',
                'dial_code' => '+880',
            ],
            [
                'en' => 'Barbados',
                'ar' => 'باربادوس',
                'iso_code' => 'BB',
                'dial_code' => '+1246',
            ],
            [
                'en' => 'Belarus',
                'ar' => 'بيلاروسيا',
                'iso_code' => 'BY',
                'dial_code' => '+375',
            ],
            [
                'en' => 'Belgium',
                'ar' => 'بلجيكا',
                'iso_code' => 'BE',
                'dial_code' => '+32',
            ],
            [
                'en' => 'Belize',
                'ar' => 'بليز',
                'iso_code' => 'BZ',
                'dial_code' => '+501',
            ],
            [
                'en' => 'Benin',
                'ar' => 'بنين',
                'iso_code' => 'BJ',
                'dial_code' => '+229',
            ],
            [
                'en' => 'Bhutan',
                'ar' => 'بوتان',
                'iso_code' => 'BT',
                'dial_code' => '+975',
            ],
            [
                'en' => 'Bolivia',
                'ar' => 'بوليفيا',
                'iso_code' => 'BO',
                'dial_code' => '+591',
            ],
            [
                'en' => 'Bosnia and Herzegovina',
                'ar' => 'البوسنة والهرسك',
                'iso_code' => 'BA',
                'dial_code' => '+387',
            ],
            [
                'en' => 'Botswana',
                'ar' => 'بوتسوانا',
                'iso_code' => 'BW',
                'dial_code' => '+267',
            ],
            [
                'en' => 'Brazil',
                'ar' => 'البرازيل',
                'iso_code' => 'BR',
                'dial_code' => '+55',
            ],
            [
                'en' => 'Brunei',
                'ar' => 'بروناي',
                'iso_code' => 'BN',
                'dial_code' => '+673',
            ],
            [
                'en' => 'Bulgaria',
                'ar' => 'بلغاريا',
                'iso_code' => 'BG',
                'dial_code' => '+359',
            ],
            [
                'en' => 'Burkina Faso',
                'ar' => 'بوركينا فاسو',
                'iso_code' => 'BF',
                'dial_code' => '+226',
            ],
            [
                'en' => 'Burundi',
                'ar' => 'بوروندي',
                'iso_code' => 'BI',
                'dial_code' => '+257',
            ],
            [
                'en' => 'Cabo Verde',
                'ar' => 'الرأس الأخضر',
                'iso_code' => 'CV',
                'dial_code' => '+238',
            ],
            [
                'en' => 'Cambodia',
                'ar' => 'كمبوديا',
                'iso_code' => 'KH',
                'dial_code' => '+855',
            ],
            [
                'en' => 'Cameroon',
                'ar' => 'الكاميرون',
                'iso_code' => 'CM',
                'dial_code' => '+237',
            ],
            [
                'en' => 'Canada',
                'ar' => 'كندا',
                'iso_code' => 'CA',
                'dial_code' => '+1',
            ],
            [
                'en' => 'Central African Republic',
                'ar' => 'جمهورية أفريقيا الوسطى',
                'iso_code' => 'CF',
                'dial_code' => '+236',
            ],
            [
                'en' => 'Chad',
                'ar' => 'تشاد',
                'iso_code' => 'TD',
                'dial_code' => '+235',
            ],
            [
                'en' => 'Chile',
                'ar' => 'تشيلي',
                'iso_code' => 'CL',
                'dial_code' => '+56',
            ],
            [
                'en' => 'China',
                'ar' => 'الصين',
                'iso_code' => 'CN',
                'dial_code' => '+86',
            ],
            [
                'en' => 'Colombia',
                'ar' => 'كولومبيا',
                'iso_code' => 'CO',
                'dial_code' => '+57',
            ],
            [
                'en' => 'Comoros',
                'ar' => 'جزر القمر',
                'iso_code' => 'KM',
                'dial_code' => '+269',
            ],
            [
                'en' => 'Congo (Democratic Republic)',
                'ar' => 'جمهورية الكونغو الديمقراطية',
                'iso_code' => 'CD',
                'dial_code' => '+243',
            ],
            [
                'en' => 'Congo (Republic)',
                'ar' => 'جمهورية الكونغو',
                'iso_code' => 'CG',
                'dial_code' => '+242',
            ],
            [
                'en' => 'Costa Rica',
                'ar' => 'كوستاريكا',
                'iso_code' => 'CR',
                'dial_code' => '+506',
            ],
            [
                'en' => 'Croatia',
                'ar' => 'كرواتيا',
                'iso_code' => 'HR',
                'dial_code' => '+385',
            ],
            [
                'en' => 'Cuba',
                'ar' => 'كوبا',
                'iso_code' => 'CU',
                'dial_code' => '+53',
            ],
            [
                'en' => 'Cyprus',
                'ar' => 'قبرص',
                'iso_code' => 'CY',
                'dial_code' => '+357',
            ],
            [
                'en' => 'Czech Republic',
                'ar' => 'التشيك',
                'iso_code' => 'CZ',
                'dial_code' => '+420',
            ],
            [
                'en' => 'Denmark',
                'ar' => 'الدنمارك',
                'iso_code' => 'DK',
                'dial_code' => '+45',
            ],
            [
                'en' => 'Djibouti',
                'ar' => 'جيبوتي',
                'iso_code' => 'DJ',
                'dial_code' => '+253',
            ],
            [
                'en' => 'Dominica',
                'ar' => 'دومينيكا',
                'iso_code' => 'DM',
                'dial_code' => '+1767',
            ],
            [
                'en' => 'Dominican Republic',
                'ar' => 'جمهورية الدومينيكان',
                'iso_code' => 'DO',
                'dial_code' => '+1809',
            ],
            [
                'en' => 'Ecuador',
                'ar' => 'الإكوادور',
                'iso_code' => 'EC',
                'dial_code' => '+593',
            ],
            [
                'en' => 'Egypt',
                'ar' => 'مصر',
                'iso_code' => 'EG',
                'dial_code' => '+20',
            ],
            [
                'en' => 'El Salvador',
                'ar' => 'السلفادور',
                'iso_code' => 'SV',
                'dial_code' => '+503',
            ],
            [
                'en' => 'Equatorial Guinea',
                'ar' => 'غينيا الاستوائية',
                'iso_code' => 'GQ',
                'dial_code' => '+240',
            ],
            [
                'en' => 'Eritrea',
                'ar' => 'إريتريا',
                'iso_code' => 'ER',
                'dial_code' => '+291',
            ],
            [
                'en' => 'Estonia',
                'ar' => 'إستونيا',
                'iso_code' => 'EE',
                'dial_code' => '+372',
            ],
            [
                'en' => 'Eswatini',
                'ar' => 'إسواتيني',
                'iso_code' => 'SZ',
                'dial_code' => '+268',
            ],
            [
                'en' => 'Ethiopia',
                'ar' => 'إثيوبيا',
                'iso_code' => 'ET',
                'dial_code' => '+251',
            ],
            [
                'en' => 'Fiji',
                'ar' => 'فيجي',
                'iso_code' => 'FJ',
                'dial_code' => '+679',
            ],
            [
                'en' => 'Finland',
                'ar' => 'فنلندا',
                'iso_code' => 'FI',
                'dial_code' => '+358',
            ],
            [
                'en' => 'France',
                'ar' => 'فرنسا',
                'iso_code' => 'FR',
                'dial_code' => '+33',
            ],
            [
                'en' => 'Gabon',
                'ar' => 'الغابون',
                'iso_code' => 'GA',
                'dial_code' => '+241',
            ],
            [
                'en' => 'Gambia',
                'ar' => 'غامبيا',
                'iso_code' => 'GM',
                'dial_code' => '+220',
            ],
            [
                'en' => 'Georgia',
                'ar' => 'جورجيا',
                'iso_code' => 'GE',
                'dial_code' => '+995',
            ],
            [
                'en' => 'Germany',
                'ar' => 'ألمانيا',
                'iso_code' => 'DE',
                'dial_code' => '+49',
            ],
            [
                'en' => 'Ghana',
                'ar' => 'غانا',
                'iso_code' => 'GH',
                'dial_code' => '+233',
            ],
            [
                'en' => 'Greece',
                'ar' => 'اليونان',
                'iso_code' => 'GR',
                'dial_code' => '+30',
            ],
            [
                'en' => 'Grenada',
                'ar' => 'غرينادا',
                'iso_code' => 'GD',
                'dial_code' => '+1473',
            ],
            [
                'en' => 'Guatemala',
                'ar' => 'غواتيمالا',
                'iso_code' => 'GT',
                'dial_code' => '+502',
            ],
            [
                'en' => 'Guinea',
                'ar' => 'غينيا',
                'iso_code' => 'GN',
                'dial_code' => '+224',
            ],
            [
                'en' => 'Guinea-Bissau',
                'ar' => 'غينيا بيساو',
                'iso_code' => 'GW',
                'dial_code' => '+245',
            ],
            [
                'en' => 'Guyana',
                'ar' => 'غيانا',
                'iso_code' => 'GY',
                'dial_code' => '+592',
            ],
            [
                'en' => 'Haiti',
                'ar' => 'هايتي',
                'iso_code' => 'HT',
                'dial_code' => '+509',
            ],
            [
                'en' => 'Honduras',
                'ar' => 'هندوراس',
                'iso_code' => 'HN',
                'dial_code' => '+504',
            ],
            [
                'en' => 'Hungary',
                'ar' => 'المجر',
                'iso_code' => 'HU',
                'dial_code' => '+36',
            ],
            [
                'en' => 'Iceland',
                'ar' => 'آيسلندا',
                'iso_code' => 'IS',
                'dial_code' => '+354',
            ],
            [
                'en' => 'India',
                'ar' => 'الهند',
                'iso_code' => 'IN',
                'dial_code' => '+91',
            ],
            [
                'en' => 'Indonesia',
                'ar' => 'إندونيسيا',
                'iso_code' => 'ID',
                'dial_code' => '+62',
            ],
            [
                'en' => 'Iran',
                'ar' => 'إيران',
                'iso_code' => 'IR',
                'dial_code' => '+98',
            ],
            [
                'en' => 'Iraq',
                'ar' => 'العراق',
                'iso_code' => 'IQ',
                'dial_code' => '+964',
            ],
            [
                'en' => 'Ireland',
                'ar' => 'أيرلندا',
                'iso_code' => 'IE',
                'dial_code' => '+353',
            ],
            [
                'en' => 'Israel',
                'ar' => 'إسرائيل',
                'iso_code' => 'IL',
                'dial_code' => '+972',
            ],
            [
                'en' => 'Italy',
                'ar' => 'إيطاليا',
                'iso_code' => 'IT',
                'dial_code' => '+39',
            ],
            [
                'en' => 'Ivory Coast',
                'ar' => 'ساحل العاج',
                'iso_code' => 'CI',
                'dial_code' => '+225',
            ],
            [
                'en' => 'Jamaica',
                'ar' => 'جامايكا',
                'iso_code' => 'JM',
                'dial_code' => '+1876',
            ],
            [
                'en' => 'Japan',
                'ar' => 'اليابان',
                'iso_code' => 'JP',
                'dial_code' => '+81',
            ],
            [
                'en' => 'Jordan',
                'ar' => 'الأردن',
                'iso_code' => 'JO',
                'dial_code' => '+962',
            ],
            [
                'en' => 'Kazakhstan',
                'ar' => 'كازاخستان',
                'iso_code' => 'KZ',
                'dial_code' => '+7',
            ],
            [
                'en' => 'Kenya',
                'ar' => 'كينيا',
                'iso_code' => 'KE',
                'dial_code' => '+254',
            ],
            [
                'en' => 'Kiribati',
                'ar' => 'كيريباتي',
                'iso_code' => 'KI',
                'dial_code' => '+686',
            ],
            [
                'en' => 'Kuwait',
                'ar' => 'الكويت',
                'iso_code' => 'KW',
                'dial_code' => '+965',
            ],
            [
                'en' => 'Kyrgyzstan',
                'ar' => 'قيرغيزستان',
                'iso_code' => 'KG',
                'dial_code' => '+996',
            ],
            [
                'en' => 'Laos',
                'ar' => 'لاوس',
                'iso_code' => 'LA',
                'dial_code' => '+856',
            ],
            [
                'en' => 'Latvia',
                'ar' => 'لاتفيا',
                'iso_code' => 'LV',
                'dial_code' => '+371',
            ],
            [
                'en' => 'Lebanon',
                'ar' => 'لبنان',
                'iso_code' => 'LB',
                'dial_code' => '+961',
            ],
            [
                'en' => 'Lesotho',
                'ar' => 'ليسوتو',
                'iso_code' => 'LS',
                'dial_code' => '+266',
            ],
            [
                'en' => 'Liberia',
                'ar' => 'ليبيريا',
                'iso_code' => 'LR',
                'dial_code' => '+231',
            ],
            [
                'en' => 'Libya',
                'ar' => 'ليبيا',
                'iso_code' => 'LY',
                'dial_code' => '+218',
            ],
            [
                'en' => 'Liechtenstein',
                'ar' => 'ليختنشتاين',
                'iso_code' => 'LI',
                'dial_code' => '+423',
            ],
            [
                'en' => 'Lithuania',
                'ar' => 'ليتوانيا',
                'iso_code' => 'LT',
                'dial_code' => '+370',
            ],
            [
                'en' => 'Luxembourg',
                'ar' => 'لوكسمبورغ',
                'iso_code' => 'LU',
                'dial_code' => '+352',
            ],
            [
                'en' => 'Madagascar',
                'ar' => 'مدغشقر',
                'iso_code' => 'MG',
                'dial_code' => '+261',
            ],
            [
                'en' => 'Malawi',
                'ar' => 'ملاوي',
                'iso_code' => 'MW',
                'dial_code' => '+265',
            ],
            [
                'en' => 'Malaysia',
                'ar' => 'ماليزيا',
                'iso_code' => 'MY',
                'dial_code' => '+60',
            ],
            [
                'en' => 'Maldives',
                'ar' => 'المالديف',
                'iso_code' => 'MV',
                'dial_code' => '+960',
            ],
            [
                'en' => 'Mali',
                'ar' => 'مالي',
                'iso_code' => 'ML',
                'dial_code' => '+223',
            ],
            [
                'en' => 'Malta',
                'ar' => 'مالطا',
                'iso_code' => 'MT',
                'dial_code' => '+356',
            ],
            [
                'en' => 'Marshall Islands',
                'ar' => 'جزر مارشال',
                'iso_code' => 'MH',
                'dial_code' => '+692',
            ],
            [
                'en' => 'Mauritania',
                'ar' => 'موريتانيا',
                'iso_code' => 'MR',
                'dial_code' => '+222',
            ],
            [
                'en' => 'Mauritius',
                'ar' => 'موريشيوس',
                'iso_code' => 'MU',
                'dial_code' => '+230',
            ],
            [
                'en' => 'Mexico',
                'ar' => 'المكسيك',
                'iso_code' => 'MX',
                'dial_code' => '+52',
            ],
            [
                'en' => 'Micronesia',
                'ar' => 'ميكرونيزيا',
                'iso_code' => 'FM',
                'dial_code' => '+691',
            ],
            [
                'en' => 'Moldova',
                'ar' => 'مولدوفا',
                'iso_code' => 'MD',
                'dial_code' => '+373',
            ],
            [
                'en' => 'Monaco',
                'ar' => 'موناكو',
                'iso_code' => 'MC',
                'dial_code' => '+377',
            ],
            [
                'en' => 'Mongolia',
                'ar' => 'منغوليا',
                'iso_code' => 'MN',
                'dial_code' => '+976',
            ],
            [
                'en' => 'Montenegro',
                'ar' => 'الجبل الأسود',
                'iso_code' => 'ME',
                'dial_code' => '+382',
            ],
            [
                'en' => 'Morocco',
                'ar' => 'المغرب',
                'iso_code' => 'MA',
                'dial_code' => '+212',
            ],
            [
                'en' => 'Mozambique',
                'ar' => 'موزمبيق',
                'iso_code' => 'MZ',
                'dial_code' => '+258',
            ],
            [
                'en' => 'Myanmar',
                'ar' => 'ميانمار',
                'iso_code' => 'MM',
                'dial_code' => '+95',
            ],
            [
                'en' => 'Namibia',
                'ar' => 'ناميبيا',
                'iso_code' => 'NA',
                'dial_code' => '+264',
            ],
            [
                'en' => 'Nauru',
                'ar' => 'ناورو',
                'iso_code' => 'NR',
                'dial_code' => '+674',
            ],
            [
                'en' => 'Nepal',
                'ar' => 'نيبال',
                'iso_code' => 'NP',
                'dial_code' => '+977',
            ],
            [
                'en' => 'Netherlands',
                'ar' => 'هولندا',
                'iso_code' => 'NL',
                'dial_code' => '+31',
            ],
            [
                'en' => 'New Zealand',
                'ar' => 'نيوزيلندا',
                'iso_code' => 'NZ',
                'dial_code' => '+64',
            ],
            [
                'en' => 'Nicaragua',
                'ar' => 'نيكاراغوا',
                'iso_code' => 'NI',
                'dial_code' => '+505',
            ],
            [
                'en' => 'Niger',
                'ar' => 'النيجر',
                'iso_code' => 'NE',
                'dial_code' => '+227',
            ],
            [
                'en' => 'Nigeria',
                'ar' => 'نيجيريا',
                'iso_code' => 'NG',
                'dial_code' => '+234',
            ],
            [
                'en' => 'North Korea',
                'ar' => 'كوريا الشمالية',
                'iso_code' => 'KP',
                'dial_code' => '+850',
            ],
            [
                'en' => 'North Macedonia',
                'ar' => 'مقدونيا الشمالية',
                'iso_code' => 'MK',
                'dial_code' => '+389',
            ],
            [
                'en' => 'Norway',
                'ar' => 'النرويج',
                'iso_code' => 'NO',
                'dial_code' => '+47',
            ],
            [
                'en' => 'Oman',
                'ar' => 'عمان',
                'iso_code' => 'OM',
                'dial_code' => '+968',
            ],
            [
                'en' => 'Pakistan',
                'ar' => 'باكستان',
                'iso_code' => 'PK',
                'dial_code' => '+92',
            ],
            [
                'en' => 'Palau',
                'ar' => 'بالاو',
                'iso_code' => 'PW',
                'dial_code' => '+680',
            ],
            [
                'en' => 'Palestine',
                'ar' => 'فلسطين',
                'iso_code' => 'PS',
                'dial_code' => '+970',
            ],
            [
                'en' => 'Panama',
                'ar' => 'بنما',
                'iso_code' => 'PA',
                'dial_code' => '+507',
            ],
            [
                'en' => 'Papua New Guinea',
                'ar' => 'بابوا غينيا الجديدة',
                'iso_code' => 'PG',
                'dial_code' => '+675',
            ],
            [
                'en' => 'Paraguay',
                'ar' => 'باراغواي',
                'iso_code' => 'PY',
                'dial_code' => '+595',
            ],
            [
                'en' => 'Peru',
                'ar' => 'بيرو',
                'iso_code' => 'PE',
                'dial_code' => '+51',
            ],
            [
                'en' => 'Philippines',
                'ar' => 'الفلبين',
                'iso_code' => 'PH',
                'dial_code' => '+63',
            ],
            [
                'en' => 'Poland',
                'ar' => 'بولندا',
                'iso_code' => 'PL',
                'dial_code' => '+48',
            ],
            [
                'en' => 'Portugal',
                'ar' => 'البرتغال',
                'iso_code' => 'PT',
                'dial_code' => '+351',
            ],
            [
                'en' => 'Qatar',
                'ar' => 'قطر',
                'iso_code' => 'QA',
                'dial_code' => '+974',
            ],
            [
                'en' => 'Romania',
                'ar' => 'رومانيا',
                'iso_code' => 'RO',
                'dial_code' => '+40',
            ],
            [
                'en' => 'Russia',
                'ar' => 'روسيا',
                'iso_code' => 'RU',
                'dial_code' => '+7',
            ],
            [
                'en' => 'Rwanda',
                'ar' => 'رواندا',
                'iso_code' => 'RW',
                'dial_code' => '+250',
            ],
            [
                'en' => 'Saint Kitts and Nevis',
                'ar' => 'سانت كيتس ونيفيس',
                'iso_code' => 'KN',
                'dial_code' => '+1869',
            ],
            [
                'en' => 'Saint Lucia',
                'ar' => 'سانت لوسيا',
                'iso_code' => 'LC',
                'dial_code' => '+1758',
            ],
            [
                'en' => 'Saint Vincent and the Grenadines',
                'ar' => 'سانت فنسنت والغرينادين',
                'iso_code' => 'VC',
                'dial_code' => '+1784',
            ],
            [
                'en' => 'Samoa',
                'ar' => 'ساموا',
                'iso_code' => 'WS',
                'dial_code' => '+685',
            ],
            [
                'en' => 'San Marino',
                'ar' => 'سان مارينو',
                'iso_code' => 'SM',
                'dial_code' => '+378',
            ],
            [
                'en' => 'Sao Tome and Principe',
                'ar' => 'ساو تومي وبرينسيب',
                'iso_code' => 'ST',
                'dial_code' => '+239',
            ],
            [
                'en' => 'Saudi Arabia',
                'ar' => 'المملكة العربية السعودية',
                'iso_code' => 'SA',
                'dial_code' => '+966',
            ],
            [
                'en' => 'Senegal',
                'ar' => 'السنغال',
                'iso_code' => 'SN',
                'dial_code' => '+221',
            ],
            [
                'en' => 'Serbia',
                'ar' => 'صربيا',
                'iso_code' => 'RS',
                'dial_code' => '+381',
            ],
            [
                'en' => 'Seychelles',
                'ar' => 'سيشل',
                'iso_code' => 'SC',
                'dial_code' => '+248',
            ],
            [
                'en' => 'Sierra Leone',
                'ar' => 'سيراليون',
                'iso_code' => 'SL',
                'dial_code' => '+232',
            ],
            [
                'en' => 'Singapore',
                'ar' => 'سنغافورة',
                'iso_code' => 'SG',
                'dial_code' => '+65',
            ],
            [
                'en' => 'Slovakia',
                'ar' => 'سلوفاكيا',
                'iso_code' => 'SK',
                'dial_code' => '+421',
            ],
            [
                'en' => 'Slovenia',
                'ar' => 'سلوفينيا',
                'iso_code' => 'SI',
                'dial_code' => '+386',
            ],
            [
                'en' => 'Solomon Islands',
                'ar' => 'جزر سليمان',
                'iso_code' => 'SB',
                'dial_code' => '+677',
            ],
            [
                'en' => 'Somalia',
                'ar' => 'الصومال',
                'iso_code' => 'SO',
                'dial_code' => '+252',
            ],
            [
                'en' => 'South Africa',
                'ar' => 'جنوب أفريقيا',
                'iso_code' => 'ZA',
                'dial_code' => '+27',
            ],
            [
                'en' => 'South Korea',
                'ar' => 'كوريا الجنوبية',
                'iso_code' => 'KR',
                'dial_code' => '+82',
            ],
            [
                'en' => 'South Sudan',
                'ar' => 'جنوب السودان',
                'iso_code' => 'SS',
                'dial_code' => '+211',
            ],
            [
                'en' => 'Spain',
                'ar' => 'إسبانيا',
                'iso_code' => 'ES',
                'dial_code' => '+34',
            ],
            [
                'en' => 'Sri Lanka',
                'ar' => 'سريلانكا',
                'iso_code' => 'LK',
                'dial_code' => '+94',
            ],
            [
                'en' => 'Sudan',
                'ar' => 'السودان',
                'iso_code' => 'SD',
                'dial_code' => '+249',
            ],
            [
                'en' => 'Suriname',
                'ar' => 'سورينام',
                'iso_code' => 'SR',
                'dial_code' => '+597',
            ],
            [
                'en' => 'Sweden',
                'ar' => 'السويد',
                'iso_code' => 'SE',
                'dial_code' => '+46',
            ],
            [
                'en' => 'Switzerland',
                'ar' => 'سويسرا',
                'iso_code' => 'CH',
                'dial_code' => '+41',
            ],
            [
                'en' => 'Syria',
                'ar' => 'سوريا',
                'iso_code' => 'SY',
                'dial_code' => '+963',
            ],
            [
                'en' => 'Taiwan',
                'ar' => 'تايوان',
                'iso_code' => 'TW',
                'dial_code' => '+886',
            ],
            [
                'en' => 'Tajikistan',
                'ar' => 'طاجيكستان',
                'iso_code' => 'TJ',
                'dial_code' => '+992',
            ],
            [
                'en' => 'Tanzania',
                'ar' => 'تنزانيا',
                'iso_code' => 'TZ',
                'dial_code' => '+255',
            ],
            [
                'en' => 'Thailand',
                'ar' => 'تايلاند',
                'iso_code' => 'TH',
                'dial_code' => '+66',
            ],
            [
                'en' => 'Timor-Leste',
                'ar' => 'تيمور الشرقية',
                'iso_code' => 'TL',
                'dial_code' => '+670',
            ],
            [
                'en' => 'Togo',
                'ar' => 'توغو',
                'iso_code' => 'TG',
                'dial_code' => '+228',
            ],
            [
                'en' => 'Tonga',
                'ar' => 'تونغا',
                'iso_code' => 'TO',
                'dial_code' => '+676',
            ],
            [
                'en' => 'Trinidad and Tobago',
                'ar' => 'ترينيداد وتوباغو',
                'iso_code' => 'TT',
                'dial_code' => '+1868',
            ],
            [
                'en' => 'Tunisia',
                'ar' => 'تونس',
                'iso_code' => 'TN',
                'dial_code' => '+216',
            ],
            [
                'en' => 'Turkey',
                'ar' => 'تركيا',
                'iso_code' => 'TR',
                'dial_code' => '+90',
            ],
            [
                'en' => 'Turkmenistan',
                'ar' => 'تركمانستان',
                'iso_code' => 'TM',
                'dial_code' => '+993',
            ],
            [
                'en' => 'Tuvalu',
                'ar' => 'توفالو',
                'iso_code' => 'TV',
                'dial_code' => '+688',
            ],
            [
                'en' => 'Uganda',
                'ar' => 'أوغندا',
                'iso_code' => 'UG',
                'dial_code' => '+256',
            ],
            [
                'en' => 'Ukraine',
                'ar' => 'أوكرانيا',
                'iso_code' => 'UA',
                'dial_code' => '+380',
            ],
            [
                'en' => 'United Arab Emirates',
                'ar' => 'الإمارات العربية المتحدة',
                'iso_code' => 'AE',
                'dial_code' => '+971',
            ],
            [
                'en' => 'United Kingdom',
                'ar' => 'المملكة المتحدة',
                'iso_code' => 'GB',
                'dial_code' => '+44',
            ],
            [
                'en' => 'United States',
                'ar' => 'الولايات المتحدة',
                'iso_code' => 'US',
                'dial_code' => '+1',
            ],
            [
                'en' => 'Uruguay',
                'ar' => 'أوروغواي',
                'iso_code' => 'UY',
                'dial_code' => '+598',
            ],
            [
                'en' => 'Uzbekistan',
                'ar' => 'أوزبكستان',
                'iso_code' => 'UZ',
                'dial_code' => '+998',
            ],
            [
                'en' => 'Vanuatu',
                'ar' => 'فانواتو',
                'iso_code' => 'VU',
                'dial_code' => '+678',
            ],
            [
                'en' => 'Vatican City',
                'ar' => 'الفاتيكان',
                'iso_code' => 'VA',
                'dial_code' => '+379',
            ],
            [
                'en' => 'Venezuela',
                'ar' => 'فنزويلا',
                'iso_code' => 'VE',
                'dial_code' => '+58',
            ],
            [
                'en' => 'Vietnam',
                'ar' => 'فيتنام',
                'iso_code' => 'VN',
                'dial_code' => '+84',
            ],
            [
                'en' => 'Yemen',
                'ar' => 'اليمن',
                'iso_code' => 'YE',
                'dial_code' => '+967',
            ],
            [
                'en' => 'Zambia',
                'ar' => 'زامبيا',
                'iso_code' => 'ZM',
                'dial_code' => '+260',
            ],
            [
                'en' => 'Zimbabwe',
                'ar' => 'زيمبابوي',
                'iso_code' => 'ZW',
                'dial_code' => '+263',
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['name->en' => $country['en']],
                [
                    'name' => ['en' => $country['en'], 'ar' => $country['ar']],
                    'iso_code' => $country['iso_code'],
                    'dial_code' => $country['dial_code'],
                ]
            );
        }
    }
}
